version: '3'
services:
  mongodb:
    container_name: mongodb-ai
    image: mongo
    ports:
      - "27017:27017"
  project1:
    container_name: be-cctv
    build:
      context: ./be-cctv
    ports:
      - "8080:8080"
    environment:
      DB_URL: mongodb://mongodb:27017/
  project2:
    container_name: streaming
    build:
      context: ./streaming
    ports:
      - "8005:8005"

